'------------------------------------------------------------------------------
' <auto-generated>
'    O código foi gerado a partir de um modelo.
'
'    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
'    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Alunos
    Public Property al_codigo As Integer
    Public Property pes_codigo As Nullable(Of Integer)
    Public Property al_ra As String

    Public Overridable Property Pessoa As Pessoa
    Public Overridable Property Matricula As ICollection(Of Matricula) = New HashSet(Of Matricula)

End Class
