'------------------------------------------------------------------------------
' <auto-generated>
'    O código foi gerado a partir de um modelo.
'
'    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
'    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class classificacao
    Public Property cla_codigo As Integer
    Public Property cla_nome As String
    Public Property cla_uf As String

    Public Overridable Property Professor As ICollection(Of Professor) = New HashSet(Of Professor)

End Class
