'------------------------------------------------------------------------------
' <auto-generated>
'    O código foi gerado a partir de um modelo.
'
'    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
'    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cursos
    Public Property cur_codigo As Integer
    Public Property cur_nome As String
    Public Property cur_valorDeCredito As Nullable(Of Integer)
    Public Property cur_sequencia As Nullable(Of Integer)

    Public Overridable Property Matricula As ICollection(Of Matricula) = New HashSet(Of Matricula)

End Class
