'------------------------------------------------------------------------------
' <auto-generated>
'    O código foi gerado a partir de um modelo.
'
'    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
'    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class List_Disciplina
    Public Property list_codigo As Integer
    Public Property mat_codigo As Nullable(Of Integer)
    Public Property dis_codigo As String

    Public Overridable Property disciplina As disciplina
    Public Overridable Property Matricula As Matricula

End Class
