'------------------------------------------------------------------------------
' <auto-generated>
'    O código foi gerado a partir de um modelo.
'
'    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
'    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pessoa
    Public Property pes_codigo As Integer
    Public Property pes_nome As String
    Public Property pes_rg As String
    Public Property pes_cpf As String
    Public Property pes_datnascimento As Nullable(Of Integer)
    Public Property pes_sexo As String
    Public Property pes_telefone As String
    Public Property pes_cidade As String
    Public Property pes_uf As String

    Public Overridable Property Alunos As ICollection(Of Alunos) = New HashSet(Of Alunos)
    Public Overridable Property Professor As ICollection(Of Professor) = New HashSet(Of Professor)

End Class
