'------------------------------------------------------------------------------
' <auto-generated>
'    O código foi gerado a partir de um modelo.
'
'    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
'    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VwMatricula
    Public Property pes_codigo As Integer
    Public Property pes_nome As String
    Public Property al_codigo As Integer
    Public Property cur_codigo As Integer
    Public Property cur_nome As String
    Public Property mat_codigo As Integer
    Public Property mat_termo As String
    Public Property mat_turma As String
    Public Property mat_ano As Nullable(Of Date)
    Public Property mat_semestre As String
    Public Property mat_valor As Nullable(Of Decimal)

End Class
