'------------------------------------------------------------------------------
' <auto-generated>
'    O código foi gerado a partir de um modelo.
'
'    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
'    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VwPessoasAlunos
    Public Property pes_codigo As Integer
    Public Property pes_nome As String
    Public Property pes_rg As String
    Public Property pes_sexo As String
    Public Property pes_datnascimento As Nullable(Of Date)
    Public Property pes_cpf As String
    Public Property pes_telefone As String
    Public Property pes_cidade As String
    Public Property pes_uf As String
    Public Property al_codigo As Integer
    Public Property al_ra As String

End Class
